version: '2'

services:
  postgresql:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: smart-warehouse_password
      POSTGRES_USER: smart-warehouse_user
      POSTGRES_DB: smart-warehouse
    ports:
      - '5432:5432'
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
      - '85:80'
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: smart@warehouse.it
      PGADMIN_DEFAULT_PASSWORD: warehouse